import type { PieceType } from '../types/chess';

export type AiWeights = {
  pieceValues: Record<PieceType, number>;
  targetCannonValue: number;
  connectedAdvisorValue: number;
  advisorTargetValue: number;
  elephantTargetValue: number;
  uncrossedPawnTargetValue: number;
  crossedPawnTargetValue: number;
  crossedPawnNearPalaceValue: number;
  meaninglessMovePenalty: number;
  lowQualityCheckPenalty: number;
  protectedMoveBonus: number;
  hangingMovePenalty: number;
  revealBonus: number;
  openingPawnBonus: number;
  edgePawnBonus: number;
  thirdSeventhPawnBonus: number;
  openingCannonTempoPenaltyRatio: number;
  openingCannonTempoMinPenalty: number;
  keySquareCenterFileBonus: number;
  keySquareNearCenterFileBonus: number;
  keySquareRiverBonus: number;
  keySquareEnemyPalaceBonus: number;
  keySquareSecondEighthFileBonus: number;
  keySquareAdjacentHiddenBonus: number;
  keySquareMaxBonus: number;
  leaveKeySquareWeakPenalty: number;
  leaveKeySquareStrongPenalty: number;
  hiddenPiecePressureBonus: number;
  importantHiddenPiecePressureBonus: number;
  hiddenPiecePressureMaxBonus: number;
  kingZoneNearBonus: number;
  kingZoneLineBonus: number;
  effectiveCheckBonus: number;
  importantThreatRatio: number;
  blockImmediateWinBonus: number;
  escapeImportantPieceBonus: number;
  possibleLossMultiplier: number;
  maxReplyGainPenaltyRatio: number;
  openingKeySquareMaxBonus: number;
  leaveKeySquareThreshold: number;
  leaveKeySquareDropThreshold: number;
  leaveKeySquareStrongThreshold: number;
  connectedAdvisorDistance: number;
  safeCaptureExchangeNet: number;
  effectiveCheckThreatValue: number;
  openingPhaseMoveLimit: number;
  openingHiddenPawnAssumptionBonus: number;
  pawnFootBlockThreatBonus: number;
  pawnElephantEyeBlockThreatBonus: number;
  pawnCannonScreenThreatBonus: number;
  pawnLineLockThreatBonus: number;
  pawnNearHiddenRookThreatBonus: number;
  structureReleaseHorseBonus: number;
  structureReleaseElephantBonus: number;
  cannonLineThreatPenalty: number;
  weakScreenAllowsPawnBlockPenalty: number;
  preserveHiddenCannonBonus: number;
  pawnLineDefenseBonus: number;
  preventEnemyRookPawnLineLockBonus: number;
  hiddenRookGuardPointBonus: number;
  enemyRookOnPawnLinePenalty: number;
  badHorseReleaseSquarePenalty: number;
  hiddenRookValueNoRevealed: number;
  hiddenRookValueOneRevealed: number;
  hiddenRookValueTwoRevealed: number;
  hiddenCannonValueNoRevealed: number;
  hiddenCannonValueOneRevealed: number;
  hiddenCannonValueTwoRevealed: number;
  hiddenHorseValueNoRevealed: number;
  hiddenHorseValueOneRevealed: number;
  hiddenHorseValueTwoRevealed: number;
  edgeCannonPressureHiddenPressureCap: number;
  safeCapturePriorityBonus: number;
  speculativeHiddenAttackPenalty: number;
  repetitiveCheckPenalty: number;
  majorActivationBonus: number;
  opponentRevealSuppressionBonus: number;
  revealChoiceRiskPenaltyBase: number;
  revealChoiceRiskHighValueExtra: number;
  hiddenPressureNonActivationCap: number;
  advisorRevealClogPenalty: number;
  advisorRevealClogNearKingPenalty: number;
  deadMajorThreatHoldBonus: number;
  defendDoomedMajorPenalty: number;
  postMoveLooseHiddenPiecePenalty: number;
  rescueLooseHiddenPieceBonus: number;
  protectedUnderAttackPenaltyCap: number;
  activationOnlyCapWhenLoosePieceExists: number;
  firstMovePawnOpeningBonus: number;
  firstMoveBlindHorseActivationPenalty: number;
  firstMoveBlindMajorActivationCap: number;
  pawnSoldierDevelopmentBonus: number;
  pawnSoldierThreatRevealedMajorBonus: number;
  pureBlindHorseActivationPenalty: number;
  pureBlindHorseStructureCap: number;
  pureBlindHorseMajorActivationCap: number;
  pawnSoldierHiddenExtraBlindHorsePenalty: number;
  pawnSoldierFollowUpHorseBonus: number;
  pawnSoldierHorseFootBlockBonus: number;
  pawnSoldierFollowUpElephantBonus: number;
  pawnSoldierCenterPreferenceBonus: number;
  pawnSoldierFollowUpAdvisorBonus: number;
  pawnSoldierAntiAdvisorForkBonus: number;
  revealedMajorCapturePriorityBonus: number;
  safeRevealedRookCaptureBonus: number;
  safeRevealedMajorCaptureBonus: number;
  pawnSoldierDelayWhenMajorCaptureAvailablePenalty: number;
  pawnSoldierWalksIntoRevealedPawnAttackPenalty: number;
  pawnSoldierDevelopmentSuppressedByPawnAttackPenalty: number;
  repeatedCheckingCyclePenalty: number;
  repeatedPositionPenalty: number;
  towardEnemyKingBonus: number;
  restrictKingMobilityBonus: number;
  attackPalaceGuardBonus: number;
  improveMajorActivityBonus: number;
  passedPawnAdvanceBonus: number;
  createNonCheckingThreatBonus: number;
  avoidAimlessMovePenalty: number;
  unsafeCapturePenalty: number;
  horsePawnLineGuardEdgeRookBonus: number;
  pawnSoldierDelayedByEdgeRookPressurePenalty: number;
  unresolvedHighValueThreatPenalty: number;
  ignoredHigherPriorityThreatPenalty: number;
  resolvedHighValueThreatBonus: number;
  multiPurposeDefenseBonus: number;
  rescuesHighValuePieceBonus: number;
  rescuesSecondaryPieceBonus: number;
  blocksHorseForkBonus: number;
  counterAttacksAttackerBonus: number;
  forcesOpponentChoiceBonus: number;
  minimumLossDefenseBonus: number;
  partialDefensePenalty: number;
  unresolvedThreatAfterDefensePenalty: number;
  materialCheckBonus: number;
  forcesBadKingMoveBonus: number;
  checkRestrictsKingMobilityBonus: number;
  meaninglessCheckPenalty: number;
  dynamicCannonOpeningAdjustment: number;
  dynamicHorseOpeningAdjustment: number;
  dynamicCannonEndgameAdjustment: number;
  dynamicHorseEndgameAdjustment: number;
  cannonWithFrameBonus: number;
  cannonNoFramePenalty: number;
  horseHighMobilityBonus: number;
  horseLowMobilityPenalty: number;
};

export const defaultAiWeights: AiWeights = {
  pieceValues: {
    king: 10000,
    rook: 500,
    cannon: 350,
    horse: 300,
    elephant: 150,
    advisor: 150,
    pawn: 80,
  },
  targetCannonValue: 360,
  connectedAdvisorValue: 280,
  advisorTargetValue: 170,
  elephantTargetValue: 140,
  uncrossedPawnTargetValue: 60,
  crossedPawnTargetValue: 120,
  crossedPawnNearPalaceValue: 145,
  meaninglessMovePenalty: -80,
  lowQualityCheckPenalty: -60,
  protectedMoveBonus: 20,
  hangingMovePenalty: -50,
  revealBonus: 20,
  openingPawnBonus: 110,
  edgePawnBonus: 35,
  thirdSeventhPawnBonus: 30,
  openingCannonTempoPenaltyRatio: 1.15,
  openingCannonTempoMinPenalty: 360,
  keySquareCenterFileBonus: 8,
  keySquareNearCenterFileBonus: 4,
  keySquareRiverBonus: 8,
  keySquareEnemyPalaceBonus: 12,
  keySquareSecondEighthFileBonus: 6,
  keySquareAdjacentHiddenBonus: 6,
  keySquareMaxBonus: 28,
  leaveKeySquareWeakPenalty: -12,
  leaveKeySquareStrongPenalty: -20,
  hiddenPiecePressureBonus: 8,
  importantHiddenPiecePressureBonus: 4,
  hiddenPiecePressureMaxBonus: 32,
  kingZoneNearBonus: 25,
  kingZoneLineBonus: 15,
  effectiveCheckBonus: 35,
  importantThreatRatio: 0.12,
  blockImmediateWinBonus: 70,
  escapeImportantPieceBonus: 45,
  possibleLossMultiplier: 1.8,
  maxReplyGainPenaltyRatio: 0.25,
  openingKeySquareMaxBonus: 4,
  leaveKeySquareThreshold: 16,
  leaveKeySquareDropThreshold: 8,
  leaveKeySquareStrongThreshold: 22,
  connectedAdvisorDistance: 3,
  safeCaptureExchangeNet: 250,
  effectiveCheckThreatValue: 350,
  openingPhaseMoveLimit: 12,
  openingHiddenPawnAssumptionBonus: 10,
  pawnFootBlockThreatBonus: 18,
  pawnElephantEyeBlockThreatBonus: 14,
  pawnCannonScreenThreatBonus: 12,
  pawnLineLockThreatBonus: 22,
  pawnNearHiddenRookThreatBonus: 16,
  structureReleaseHorseBonus: 36,
  structureReleaseElephantBonus: 28,
  cannonLineThreatPenalty: -24,
  weakScreenAllowsPawnBlockPenalty: -18,
  preserveHiddenCannonBonus: 16,
  pawnLineDefenseBonus: 24,
  preventEnemyRookPawnLineLockBonus: 32,
  hiddenRookGuardPointBonus: 18,
  enemyRookOnPawnLinePenalty: -30,
  badHorseReleaseSquarePenalty: -18,
  hiddenRookValueNoRevealed: 380,
  hiddenRookValueOneRevealed: 300,
  hiddenRookValueTwoRevealed: 210,
  hiddenCannonValueNoRevealed: 300,
  hiddenCannonValueOneRevealed: 250,
  hiddenCannonValueTwoRevealed: 190,
  hiddenHorseValueNoRevealed: 280,
  hiddenHorseValueOneRevealed: 230,
  hiddenHorseValueTwoRevealed: 170,
  edgeCannonPressureHiddenPressureCap: 8,
  safeCapturePriorityBonus: 35,
  speculativeHiddenAttackPenalty: -15,
  repetitiveCheckPenalty: -45,
  majorActivationBonus: 45,
  opponentRevealSuppressionBonus: 12,
  revealChoiceRiskPenaltyBase: 90,
  revealChoiceRiskHighValueExtra: 40,
  hiddenPressureNonActivationCap: 16,
  advisorRevealClogPenalty: -70,
  advisorRevealClogNearKingPenalty: -110,
  deadMajorThreatHoldBonus: 70,
  defendDoomedMajorPenalty: -80,
  postMoveLooseHiddenPiecePenalty: -110,
  rescueLooseHiddenPieceBonus: 90,
  protectedUnderAttackPenaltyCap: -20,
  activationOnlyCapWhenLoosePieceExists: 20,
  firstMovePawnOpeningBonus: 80,
  firstMoveBlindHorseActivationPenalty: -90,
  firstMoveBlindMajorActivationCap: 20,
  pawnSoldierDevelopmentBonus: 70,
  pawnSoldierThreatRevealedMajorBonus: 50,
  pureBlindHorseActivationPenalty: -80,
  pureBlindHorseStructureCap: 15,
  pureBlindHorseMajorActivationCap: 0,
  pawnSoldierHiddenExtraBlindHorsePenalty: -60,
  pawnSoldierFollowUpHorseBonus: 45,
  pawnSoldierHorseFootBlockBonus: 35,
  pawnSoldierFollowUpElephantBonus: 25,
  pawnSoldierCenterPreferenceBonus: 30,
  pawnSoldierFollowUpAdvisorBonus: 35,
  pawnSoldierAntiAdvisorForkBonus: 30,
  revealedMajorCapturePriorityBonus: 90,
  safeRevealedRookCaptureBonus: 120,
  safeRevealedMajorCaptureBonus: 0,
  pawnSoldierDelayWhenMajorCaptureAvailablePenalty: -80,
  pawnSoldierWalksIntoRevealedPawnAttackPenalty: -120,
  pawnSoldierDevelopmentSuppressedByPawnAttackPenalty: -80,
  repeatedCheckingCyclePenalty: -300,
  repeatedPositionPenalty: -250,
  towardEnemyKingBonus: 25,
  restrictKingMobilityBonus: 45,
  attackPalaceGuardBonus: 35,
  improveMajorActivityBonus: 20,
  passedPawnAdvanceBonus: 30,
  createNonCheckingThreatBonus: 40,
  avoidAimlessMovePenalty: -80,
  unsafeCapturePenalty: -120,
  horsePawnLineGuardEdgeRookBonus: 80,
  pawnSoldierDelayedByEdgeRookPressurePenalty: -90,
  unresolvedHighValueThreatPenalty: -250,
  ignoredHigherPriorityThreatPenalty: -180,
  resolvedHighValueThreatBonus: 120,
  multiPurposeDefenseBonus: 180,
  rescuesHighValuePieceBonus: 130,
  rescuesSecondaryPieceBonus: 70,
  blocksHorseForkBonus: 80,
  counterAttacksAttackerBonus: 90,
  forcesOpponentChoiceBonus: 60,
  minimumLossDefenseBonus: 90,
  partialDefensePenalty: -90,
  unresolvedThreatAfterDefensePenalty: -180,
  materialCheckBonus: 80,
  forcesBadKingMoveBonus: 60,
  checkRestrictsKingMobilityBonus: 50,
  meaninglessCheckPenalty: -100,
  dynamicCannonOpeningAdjustment: 20,
  dynamicHorseOpeningAdjustment: -10,
  dynamicCannonEndgameAdjustment: -40,
  dynamicHorseEndgameAdjustment: 50,
  cannonWithFrameBonus: 30,
  cannonNoFramePenalty: -20,
  horseHighMobilityBonus: 20,
  horseLowMobilityPenalty: -30,
};
